### ISSUE TITLE
Package

### ISSUE THREAD

**Issue by theavege** [SaschaWillems/dglOpenGL#10]
<b>Hello!</b>

Thanks for your project.
Could you make [dglOpenGL](https://github.com/SaschaWillems/dglOpenGL) in the form of a package?

<i>Thanks.</i>

**Comment by SaschaWillems** [comment]
Can you elaborate? "package is an arbitrary term and I'm not sure what you're asking for.

**Comment by theavege** [comment]
I want to add your project in my through ```lazbuild --add-package-link```.
I told about package for Lazarus.
If it is possible.

**Comment by SaschaWillems** [comment]
Sorry, I haven't been doing anything Pascal/Delphi related in ages and I don't know anything about lazarus packages. I won't be able to provide that.

**Comment by theavege** [comment]
@SaschaWillems  I have done. Could you, please, approve my [PR](https://github.com/SaschaWillems/dglOpenGL/pull/11)?
