### ISSUE TITLE
GPU_DEVICE should be in a conditional

### ISSUE THREAD

**Issue by dejeanpaca** [SaschaWillems/dglOpenGL#2]
On a platform other than windows, the GPU_DEVICE structure should be in a conditional, or restore the TRect type which is also a windows specific thing. Afaik, I don't think GPU_DEVICE is used outside of windows, so no need to restore the TRect conditional.

**Comment by basisbit** [comment]
TRect is not a windows specific thing, but instead rather a freepascal runtimelibrary (RTL) specific thing. So for most applications which start as console app, this breaks compilation.

**Comment by dejeanpaca** [comment]
Ok then. But still, as far as I can see PGPU_DEVICE is used only with a wgl function, so maybe it shouldn't be defined for other platforms aside windows?

**Comment by neurolabusc** [comment]
@SaschaWillems  I think issues 2 and 3 are one and the same.
