### ISSUE TITLE
TRect not part of default fpc

### ISSUE THREAD

**Issue by basisbit** [SaschaWillems/dglOpenGL#3]
Please add this definition again. TRect is not defined in fpc but instead only in the RTL (for example lazarus / windows/...) and thus not having these lines breaks building for various command-line targets. (this would effectively revert your last two commits)

{$IFDEF FPC}
    TRect = packed record
      Left, Top, Right, Bottom: Longint;
    end;
{$ENDIF}

**Comment by SaschaWillems** [comment]
I made this change upon request from another FPC user (see #1). I'm not sure if removing it would be the correct way.

**Comment by basisbit** [comment]
*bump* this is still broken for any project not using the fpc RTL and current fpc.

**Comment by neurolabusc** [comment]
@SaschaWillems - I think the optimal solution is to remove the definition of GPU_Device when you compile on UNIX. The rcVirtualScreen is only used when compiling from Windows. The following IFDEF block allows the code to compile on MacOS/Linux without requiring TRect to be defined. The other solution is to add the `types` unit to your `USES` section.
```
  {$IFDEF DGL_WIN}
  PGPU_DEVICE = ^GPU_DEVICE;
  GPU_DEVICE = record
    cb: DWORD;
    DeviceName: array [0..31] of AnsiChar;
    DeviceString: array [0..127] of AnsiChar;
    Flags: DWORD;
    rcVirtualScreen: TRect;
  end;
  {$ENDIF} 
```

**Comment by basisbit** [comment]
@neurolabusc I think you mixed up the issues. This one is about TRect, not about the GPU_DEVICE pointer, that is issue #2

**Comment by basisbit** [comment]
TRect is needed for certain opengl functions, so it is independent from #2

**Comment by neurolabusc** [comment]
They are the same issue: in the dglOpenGL unit the only place TRect is used is for the GPU_DEVICE structure.  Since the structure is not used by Unix, there is no need to define TRect. If you use TRect for other units, just put `types` in your `USES` section to avoid type collisions.

**Comment by neurolabusc** [comment]
@SaschaWillems the diff below will remove the dependency on TRect for Unix systems. The explicit paths to libraries seem required by recent versions of FPC on [macOS](https://gist.github.com/frostney/1044116). 

@@ -391,7 +391,7 @@ type
 
   PGLMatrixd4 = ^TGLMatrixd4;
   PVector4i = ^TVector4i;
+{$IFDEF DGL_WIN}
   PGPU_DEVICE = ^GPU_DEVICE;
   GPU_DEVICE = record
    cb: DWORD;
    DeviceName: array [0..31] of AnsiChar;
    DeviceString: array [0..127] of AnsiChar;
    Flags: DWORD;
    rcVirtualScreen: TRect;
   end;
+{$ENDIF}
 
@@ -14767,8 +14767,11 @@ const
 {$IFDEF darwin}
-OPENGL_LIBNAME = 'libGL.dylib';
-GLU_LIBNAME = 'libGLU.dylib';
+//provide explicit paths for macOS libraries: https://gist.github.com/frostney/1044116
+//OPENGL_LIBNAME = 'libGL.dylib';
+//GLU_LIBNAME = 'libGLU.dylib';
+OPENGL_LIBNAME = '/System/Library/Frameworks/OpenGL.framework/Libraries/libGL.dylib';
+GLU_LIBNAME = '/System/Library/Frameworks/OpenGL.framework/Libraries/libGLU.dylib';
{$ELSE}

@@ -20623,9 +20626,9 @@ end;
-{$IFDEF CPU386}
+{$IFDEF CPU386}{$IFNDEF DARWIN}
   Set8087CW($133F);
-{$ENDIF}
+{$ENDIF}{$ENDIF}

**Comment by SaschaWillems** [comment]
Sry for the late reply, haven't done anything with FPC or Delphi for months.

@neurolabusc: Can you do a pull request with your changes so I can merge them into master?

**Comment by neurolabusc** [comment]
@SaschaWillems - I tried, but can not issue a pull-request since this repository is not owned by an organization. I have sent you a link to the modified code using your web page contact details. Thanks. I know you are busy with your Vulkan projects - keep up the good work.
