### ISSUE TITLE
Allow libGL to be loaded and function addresses to be resolved by SDL

### ISSUE THREAD

**Issue by s09bQ5** [SaschaWillems/dglOpenGL#7]
SDL allows to create a GL context for a video device and will resolve GL function addresses for the GL library it uses. It is an error prone step to then try to load libGL again, not knowing the correct path.
Over at [UltraStar-Deluxe](https://github.com/UltraStar-Deluxe/USDX) I proposed a commit s09bQ5/USDX@c4e1908c84677ca1e3a81013d75ecd735bd53119 that optionally uses SDL to handle libGL, but there are fears that modifying dglOpenGL will complicate making an update. Is there any chance of getting something like this into one of the next dglOpenGL releases?

For SDL in Pascal we are using [this](https://github.com/ev1313/Pascal-SDL-2-Headers).

**Comment by SaschaWillems** [comment]
Sry, I'm not actively working with Delphi/Pascal anymore. So if you need such a feature you'd have to implement it yourself and submit a PR. Or maybe ask over at the [delphigl.com forums](https://delphigl.com/forum/index.php).
